[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "chain_state"
requires-python = ">=3.10"
version = "0.0.1"
dependencies = [
    "python-dotenv~=1.0.0",
    "requests~=2.30.0",
    "web3~=6.3.0",
    "SQLAlchemy~=2.0.13"
]
